name: 'Name ofc'
description: 'Description #1 ofc'
inputs:
  compile_result:
    required: true
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  pr_number:
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'node12'
  main: 'dist/index.js'