name: 'Post warnings/errors as PR comment'
description: 'GitHub action that parses the compile output and will create PR comment with warnings/errors listed'
inputs:
  compile_result_file:
    description: 'File which contains compilation result'
    required: true
  compiler:
    description: 'Which compiler was used to produce the output. MSVC/GNU/CLANG'
    required: true
    default: GNU
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    required: true
    default: ${{ github.token }}
  work_dir:
    description: 'Action work directory'
    required: true
    default: ${{ github.workspace }}
  exclude_dir:
    description: 'Full path to the directory that should be ignored'
  pull_request_number:
    description: 'Github Pull Request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  comment_title:
    description: 'Comment title that will be displayed on top of the comment. Used also to determine whether
                  comment already exists and should be edited or not'
    required: true
    default: COMPILE RESULT
  num_lines_to_display:
    description: 'Number of lines for code snippet which will be displayed for each error/warning'
    default: 5
  debug_output:
    description: 'Use this input to generate debug prints'
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: "book-open"
  color: "white"
